[pytest]
# Adds the current directory (src) to the python path automatically
pythonpath = .

# Tells pytest where to look for tests by default
testpaths = app/tests
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
# Optional: Add default flags (v for verbose, s to show print statements)
addopts = -v -s

# Tells pytest to ignore warning noise (like SQLAlchemy or Deprecation warnings)
filterwarnings =
    ignore::DeprecationWarning